// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(grunt) {
    var cfg, projectFiles;
    require("load-grunt-tasks")(grunt);
    cfg = {
      app: '.',
      tmp: '.tmp'
    };
    projectFiles = ['ngWatchWatcher/watchWatcher.module.js', 'ngWatchWatcher/scopeCounters.factory.js', 'ngWatchWatcher/watchCounters.factory.js', 'ngWatchWatcher/watchLight.controller.js', 'ngWatchWatcher/watchLight.directive.js'];
    grunt.initConfig({
      cfg: cfg,
      express: {
        app: {
          options: {
            port: 3001,
            hostname: "0.0.0.0",
            bases: [__dirname],
            livereload: true
          }
        }
      },
      open: {
        app: {
          path: 'http://localhost:<%= express.app.options.port %>'
        }
      },
      watch: {
        app: {
          options: {
            livereload: true
          },
          files: ["<%= cfg.app %>/*.html", "<%= cfg.app %>/{,*/}*.css", "<%= cfg.app %>/*.js", "<%= cfg.app %>/{,*/}*.js"]
        }
      },
      uglify: {
        min: {
          files: {
            'ngWatchWatcher.min.js': projectFiles
          }
        }
      },
      concat: {
        noMin: {
          files: {
            'ngWatchWatcher.js': projectFiles
          }
        }
      }
    });
    grunt.registerTask("server", ["express", "open", 'watch']);
    grunt.registerTask("build", ["uglify", "concat"]);
    return grunt.registerTask("default", ["build", "server"]);
  };

}).call(this);
