// Generated by CoffeeScript 1.7.1
(function() {
  describe('scopeCounters.factory', function() {
    var sampleApp, scope, scopeCounters;
    scope = void 0;
    scopeCounters = void 0;
    sampleApp = void 0;
    beforeEach(function() {
      angular.mock.module('watchWatcher');
      return angular.mock.inject(function(_scopeCounters_) {
        return scopeCounters = _scopeCounters_;
      });
    });
    it('is defined', function() {
      return expect(scopeCounters).toBeDefined();
    });
    describe('byEl', function() {
      return it('is a function', function() {
        return expect(typeof scopeCounters.byEl).toBeDefined();
      });
    });
    return describe('byScope', function() {
      return it('is a function', function() {
        return expect(typeof scopeCounters.byScope).toBeDefined();
      });
    });
  });

}).call(this);
